"use client";
import {useState} from "react";
type Route={distanceMiles:number;durationMinutes:number;coordinates:[number,number][]};
export default function OpenRoutePreview(){
 const [pickup,setPickup]=useState(""),[destination,setDestination]=useState(""),[route,setRoute]=useState<Route|null>(null),[price,setPrice]=useState<number|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 async function calculate(e:React.FormEvent){e.preventDefault();setLoading(true);setRoute(null);setPrice(null);setMessage("");
 try{const res=await fetch("/api/recovery/open-estimate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pickupPostcode:pickup,destinationPostcode:destination})});const data=await res.json();if(!res.ok)throw Error(data.error||"Unable to check route");setRoute(data.route||null);setPrice(typeof data.estimatedPriceGbp==="number"?data.estimatedPriceGbp:null);setMessage(data.message||data.disclaimer||"");}catch{setMessage("Price to be confirmed by recovery drivers");}finally{setLoading(false)}}
 return <section className="dashboard-card" aria-label="Open route preview"><h2>Check a recovery route</h2><p>Free postcode lookup. Road mileage needs a configured routing provider. Locations are approximate postcode centres; confirm the address with the driver.</p><form onSubmit={calculate} className="form-grid"><label>Pickup postcode<input value={pickup} onChange={e=>setPickup(e.target.value)} required placeholder="e.g. SW1A 1AA"/></label><label>Destination postcode<input value={destination} onChange={e=>setDestination(e.target.value)} required placeholder="e.g. M1 1AA"/></label><button className="button primary" disabled={loading}>{loading?"Checking route…":"Check driving route & estimate"}</button></form>{route&&<p><strong>{route.distanceMiles.toFixed(2)} road miles</strong> · Approx. {route.durationMinutes} driving minutes (not driver arrival ETA)</p>}{price!==null?<p><strong>ESTIMATED RECOVERY PRICE (£{price.toFixed(2)})</strong> — drivers may quote differently.</p>:<p role="status">{message||"Price to be confirmed by recovery drivers"}</p>}{route&&<details><summary>Route coordinates available</summary><p>Map tiles require an attribution-compliant map integration; route geometry is ready for Leaflet.</p></details>}<p><small>Postcode data: Postcodes.io. Routing: configured OSRM-compatible provider; no public demo production dependency.</small></p></section>;
}
