"use client";
import {useState} from "react";
import RecoveryRouteMap from "./recovery-route-map";
type Route={distanceMiles:number;durationMinutes:number;coordinates:[number,number][];pickup:{latitude:number;longitude:number};destination:{latitude:number;longitude:number}};
export default function OpenRoutePreview(){
 const [pickup,setPickup]=useState(""),[destination,setDestination]=useState(""),[vehicleType,setVehicleType]=useState("Car"),[runningStatus,setRunningStatus]=useState("Running"),[lockedWheels,setLockedWheels]=useState(false),[accident,setAccident]=useState(false),[urgent,setUrgent]=useState(false),[loadingDifficulty,setLoadingDifficulty]=useState(false),[specialEquipment,setSpecialEquipment]=useState(false),[route,setRoute]=useState<Route|null>(null),[price,setPrice]=useState<number|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 async function calculate(e:React.FormEvent){e.preventDefault();setLoading(true);setRoute(null);setPrice(null);setMessage("");
 try{const res=await fetch("/api/recovery/open-estimate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pickupPostcode:pickup,destinationPostcode:destination,vehicleType,runningStatus,lockedWheels,accident,urgent,loadingDifficulty,specialEquipment})});const data=await res.json();if(!res.ok)throw Error(data.error||"Unable to check route");setRoute(data.route||null);setPrice(typeof data.estimatedPriceGbp==="number"?data.estimatedPriceGbp:null);setMessage(data.message||data.disclaimer||"");}catch{setMessage("Price to be confirmed by recovery drivers");}finally{setLoading(false)}}
 return <section className="dashboard-card" aria-label="Open route preview"><h2>Check a recovery route</h2><p>Free postcode lookup. Road mileage needs a configured routing provider. Locations are approximate postcode centres; confirm the address with the driver.</p><form onSubmit={calculate} className="form-grid"><label>Pickup postcode<input value={pickup} onChange={e=>setPickup(e.target.value)} required placeholder="e.g. SW1A 1AA"/></label><label>Destination postcode<input value={destination} onChange={e=>setDestination(e.target.value)} required placeholder="e.g. M1 1AA"/></label><label>Vehicle type<select value={vehicleType} onChange={e=>setVehicleType(e.target.value)}><option>Car</option><option>Van</option><option>Motorbike</option></select></label><label>Vehicle condition<select value={runningStatus} onChange={e=>setRunningStatus(e.target.value)}><option>Running</option><option>Non-running</option></select></label><label><input type="checkbox" checked={lockedWheels} onChange={e=>setLockedWheels(e.target.checked)}/> Locked wheels</label><label><input type="checkbox" checked={accident} onChange={e=>setAccident(e.target.checked)}/> Accident recovery</label><label><input type="checkbox" checked={urgent} onChange={e=>setUrgent(e.target.checked)}/> Urgent recovery</label><label><input type="checkbox" checked={loadingDifficulty} onChange={e=>setLoadingDifficulty(e.target.checked)}/> Difficult loading</label><label><input type="checkbox" checked={specialEquipment} onChange={e=>setSpecialEquipment(e.target.checked)}/> Special equipment required</label><button className="button primary" disabled={loading}>{loading?"Checking route…":"Check driving route & estimate"}</button></form>{route&&<p><strong>{route.distanceMiles.toFixed(2)} road miles</strong> · Approx. {route.durationMinutes} driving minutes (not driver arrival ETA)</p>}{price!==null?<p><strong>ESTIMATED RECOVERY PRICE (£{price.toFixed(2)})</strong> — drivers may quote differently.</p>:<p role="status">{message||"Price to be confirmed by recovery drivers"}</p>}<RecoveryRouteMap route={route}/><p><small>Postcode data: Postcodes.io. Routing: OpenRouteService when server configured. Demo estimates require approved production rates.</small></p></section>;
}
