import Link from "next/link";
import InstallAppButton from "../install-app-button";

const trust=[["UK-WIDE","Marketplace Coverage"],["VERIFIED","Recovery Professionals"],["24/7","Request Access"],["TRANSPARENT","Driver Offers"]];
const mission=[["01","Simple requests","Make it easier to explain where recovery is needed and what help is required."],["02","Customer choice","Give motorists the ability to compare suitable offers before choosing."],["03","Trusted access","Build verification, document checks and reviews into the marketplace experience."],["04","Independent business","Help UK recovery professionals connect with suitable nearby opportunities."]];
const safety=["Driver and company verification","Insurance and document checks","Customer review framework","Transparent offer comparison","Secure account access","Marketplace safety controls"];

function Header(){return <header className="uk-header"><div className="uk-nav"><Link href="/" className="uk-logo"><span>UK</span><b>Recovery</b></Link><nav className="about-nav"><Link href="/">Home</Link><Link href="/recovery/request">Get a Quote</Link><Link href="/how-it-works">How It Works</Link><Link href="/about" className="active">About</Link><span>EN · English</span></nav><div className="uk-account about-account"><Link href="/login">Customer Login</Link><Link href="/login?mode=signup" className="uk-create">Get Started</Link><Link href="/login?role=business">Business Login</Link><Link href="/login?role=driver">Driver Login</Link><Link href="/login?role=admin">Admin Login</Link><InstallAppButton className="header-install"/></div><button className="uk-menu" aria-label="Open menu">☰</button></div></header>}

function Footer(){return <footer className="uk-footer"><div className="footer-main"><div><Link href="/" className="uk-logo"><span>UK</span><b>Recovery</b></Link><p>UK Recovery is a marketplace connecting customers with independent recovery providers.</p><InstallAppButton/></div><div><b>Customer</b><Link href="/recovery/request">Get Recovery</Link><Link href="/how-it-works">How It Works</Link><Link href="/#services">Services</Link><Link href="/login?mode=signup">Create Account</Link></div><div><b>Drivers</b><Link href="/driver/register">Become a Driver</Link><Link href="/login?role=driver">Driver Login</Link><Link href="/driver/membership">Membership</Link></div><div><b>Company</b><Link href="/about">About</Link><span>Contact</span><span>FAQ</span></div><div><b>Legal</b><span>Terms</span><span>Privacy</span></div></div><div className="footer-bottom-new">© {new Date().getFullYear()} UK Recovery · UK-wide vehicle recovery marketplace</div></footer>}

export default function AboutPage(){return <main className="uk-home about-page"><Header/>
<section className="about-hero"><div className="about-wrap"><span className="uk-kicker">ABOUT US</span><h1>Connecting Drivers With <em>Trusted Recovery Professionals</em></h1><p>UK Recovery is being built as a nationwide marketplace connecting motorists with independent vehicle recovery professionals across the United Kingdom.</p><p>Our goal is to make finding recovery help simpler, clearer and more transparent — with one place to request help, receive suitable offers and choose who you want to recover your vehicle.</p></div></section>

<section className="about-stats"><div className="about-wrap stats-grid">{trust.map(([v,l])=><article key={v}><strong>{v}</strong><span>{l}</span></article>)}</div></section>

<section className="about-split about-wrap"><div><span className="uk-kicker">OUR STORY</span><h2>Recovery should be easier to find.</h2></div><div className="about-copy"><p>UK Recovery was created around a simple idea: finding suitable vehicle recovery should be easier.</p><p>Traditional recovery searches can mean contacting multiple companies individually. Our marketplace is designed so a customer can create one recovery request and connect with suitable independent recovery professionals.</p></div></section>

<section className="about-mission"><div className="about-wrap"><div className="uk-section-head"><span className="uk-kicker">OUR MISSION</span><h2>A clearer connection between customers and recovery professionals.</h2><p>We are building the platform around simple requests, meaningful choice and a professional marketplace experience for both sides.</p></div><div className="mission-grid">{mission.map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

<section className="about-market about-wrap"><div><span className="uk-kicker">HOW WE ARE DIFFERENT</span><h2>One Platform. <em>Multiple Recovery Professionals.</em></h2><p>UK Recovery is not one recovery company. A request can be shared with suitable nearby professionals, allowing the customer to review options rather than being automatically assigned to the cheapest provider.</p><div className="compare-chips"><span>Price</span><span>ETA</span><span>Rating</span><span>Verified status</span></div></div><div className="about-flow">{["Customer Posts Request","Nearby Suitable Drivers","Drivers Send Offers","Customer Compares","Customer Chooses"].map((x,i)=><article key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span>{i<4&&<em>→</em>}</article>)}</div></section>

<section className="audience-section"><div className="about-wrap audience-grid"><article><span className="uk-kicker">FOR CUSTOMERS</span><h2>More clarity when you need recovery.</h2><ul><li>Easy recovery request</li><li>Estimated recovery price</li><li>Multiple driver offers</li><li>Compare suitable options</li><li>Choose your preferred recovery professional</li></ul><Link href="/recovery/request" className="estimate-cta">GET A QUOTE →</Link></article><article className="dark"><span className="uk-kicker">FOR RECOVERY PROFESSIONALS</span><h2>More ways to find suitable work.</h2><ul><li>Join the marketplace</li><li>Complete verification</li><li>Choose membership</li><li>Receive suitable nearby jobs</li><li>Send offers and grow your business</li></ul><Link href="/driver/register" className="estimate-cta">BECOME A DRIVER →</Link></article></div></section>

<section className="about-safety about-wrap"><div><span className="uk-kicker">TRUST & SAFETY</span><h2>Professional standards built into the marketplace.</h2><p>Our platform is designed to support safer, clearer interactions without making guarantees that depend on individual providers or circumstances.</p></div><div className="safety-list">{safety.map(x=><span key={x}>✓ {x}</span>)}</div></section>

<section className="about-install" id="install-app"><div className="about-wrap"><div><span className="uk-kicker">INSTALLABLE WEB APP</span><h2>UK Recovery, Ready When You Need It</h2><p>Install the UK Recovery web app on a supported phone or device for faster access to recovery requests, offers and account updates.</p></div><div><InstallAppButton/><small>No app store required.</small></div></div></section>

<section className="about-final"><div className="about-wrap"><div><span className="uk-kicker">READY WHEN YOU NEED US</span><h2>Need Vehicle Recovery?</h2></div><div className="about-final-actions"><Link href="/recovery/request" className="estimate-cta">GET A QUOTE →</Link><Link href="/login?mode=signup" className="about-light-btn">CREATE ACCOUNT</Link><Link href="/driver/register" className="about-text-btn">BECOME A DRIVER →</Link></div></div></section>
<Footer/></main>}