"use client";
import Link from "next/link";
import { CSSProperties, FormEvent, useEffect, useRef, useState } from "react";
import InstallAppButton from "./install-app-button";
import PublicHeader from "./components/public-header";
import "./home-enhancements.css";

const services=[["⚡","Breakdown Recovery"],["⚠","Accident Recovery"],["↔","Vehicle Transport"],["↗","Car Towing"],["＋","Jump Start / Flat Battery Assistance"],["◉","Flat Tyre Assistance"],["◇","Motorbike Recovery"],["▰","Van Recovery"],["▤","Auction Vehicle Collection"],["⌁","Non-Running Vehicle Transport"]];
// Replace this single URL later with the approved UK Recovery hero image.
const HERO_BACKGROUND_IMAGE="https://images.unsplash.com/photo-1699542108036-1c11c6ee0da3?auto=format&fit=crop&q=82&w=2400";
const steps=[["01","REQUEST RECOVERY","Enter your pickup, destination and vehicle details."],["02","GET AN ESTIMATE","Review an indicative price, subject to the request details."],["03","RECEIVE DRIVER OFFERS","Suitable approved drivers may propose a price and ETA."],["04","COMPARE & CHOOSE","Compare independent offers and select your preferred driver."],["05","RECOVERY COMPLETED","Your chosen professional carries out the recovery."],["06","PAY DRIVER DIRECTLY","Pay the selected driver or company directly, outside the platform."]];
export default function HomePage(){
 const [pickup,setPickup]=useState("");const [destination,setDestination]=useState("");const [locationText,setLocationText]=useState("");const [quoteOpen,setQuoteOpen]=useState(false);const pickupRef=useRef<HTMLInputElement>(null);const quoteToggleRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(quoteOpen)pickupRef.current?.focus();},[quoteOpen]);
 function quote(e:FormEvent){e.preventDefault();const q=new URLSearchParams();if(pickup)q.set("pickup",pickup);if(destination)q.set("destination",destination);window.location.href="/recovery/request?"+q.toString()}
 function locate(){if(!navigator.geolocation){setLocationText("Location is not available on this device.");return}setLocationText("Finding your location…");navigator.geolocation.getCurrentPosition(({coords})=>{const v=coords.latitude.toFixed(5)+", "+coords.longitude.toFixed(5);fetch("/api/recovery/postcode?lat="+coords.latitude+"&lng="+coords.longitude).then(r=>r.json()).then(data=>{if(!data.postcode)throw new Error();setPickup(data.postcode);setLocationText("Pickup postcode detected.");}).catch(()=>setLocationText("Could not find a postcode. Enter one manually."))},()=>setLocationText("Location permission was not granted."))}
 return <main className="uk-home">
  <PublicHeader/>
  <section className="uk-hero uk-hero-photo" style={{"--hero-image":`url("${HERO_BACKGROUND_IMAGE}")`} as CSSProperties}><div className="uk-hero-shade"/><div className="uk-hero-inner hero-reference-layout">
   <div className="uk-hero-copy"><span className="uk-kicker hero-trust-badge">UK VEHICLE RECOVERY MARKETPLACE · CLIENT DEMO</span><h1>Recovery On<br/><em>Your Terms.</em></h1><p>Request vehicle recovery, compare offers from independent recovery professionals and choose your preferred driver.</p></div>
   <div className="hero-action-panel"><p className="hero-action-title">How can we help?</p><p className="hero-action-intro">Choose one option to explore our recovery marketplace.</p><div className="hero-action-buttons"><button ref={quoteToggleRef} type="button" className="hero-action-primary" aria-expanded={quoteOpen} aria-controls="homepage-quick-quote" onClick={()=>setQuoteOpen(v=>!v)}><span aria-hidden="true">↗</span> Get Recovery Quote <span aria-hidden="true">→</span></button><Link href="/recovery/nearby" className="hero-action-secondary"><span aria-hidden="true">⌖</span> Find Recovery Near Me <span aria-hidden="true">→</span></Link><Link href="/driver/register" className="hero-action-secondary"><span aria-hidden="true">▰</span> Join as a Recovery Driver <span aria-hidden="true">→</span></Link></div><p className="hero-action-notice">Read-only client demo · No live bookings or payments.</p>
   {quoteOpen&&<form id="homepage-quick-quote" className="quote-panel hero-quote-panel expanded-quote" onSubmit={quote}>
   <button type="button" className="close-quote" onClick={()=>{setQuoteOpen(false);quoteToggleRef.current?.focus()}}>Close quote form ×</button>
    <div className="hero-quote-grid">
     <label><span>Pickup postcode</span><div className="hero-input-wrap"><b>⌖</b><input ref={pickupRef} value={pickup} onChange={e=>setPickup(e.target.value)} placeholder="Enter pickup postcode" autoComplete="postal-code" required/></div></label>
     <label><span>Drop-off postcode</span><div className="hero-input-wrap"><b>●</b><input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Enter destination postcode (if known)"/></div></label>
    </div>
    <button type="button" className="use-location hero-location" onClick={locate}>⌖ Use My Current Location</button>{locationText&&<small className="location-copy">{locationText}</small>}
    <button type="submit" className="estimate-cta hero-estimate">EXPLORE YOUR RECOVERY ESTIMATE <span aria-hidden="true">→</span></button>
    <p className="hero-market-note">Client demo: explore the recovery request journey. Live bookings, driver offers and payments are not enabled.</p>
   </form>}</div>
  </div></section>

  <section className="uk-trust"><div>{[["✓","Driver approval process"],["↔","Independent price & ETA offers"],["⌖","Designed for UK postcodes"],["£","Pay driver directly"]].map(([i,t])=><article key={t}><b>{i}</b><span>{t}</span></article>)}</div></section>

  <section className="uk-section" id="services"><div className="uk-section-head"><span className="uk-kicker">RECOVERY SERVICES</span><h2>Recovery Services for Every Situation</h2><p>Explore the ten supported recovery and vehicle transport services. Each opens the existing demo request journey.</p></div><div className="uk-service-grid">{services.map(([i,t])=><Link href="/recovery/request" key={t} className="uk-service"><b>{i}</b><span>{t}</span><em>→</em></Link>)}</div></section>

  <section className="uk-how" id="how"><div className="uk-section-head"><span className="uk-kicker">HOW IT WORKS</span><h2>A Clear Journey, With You in Control</h2></div><div className="uk-steps">{steps.map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div><div className="center-action"><Link href="/how-it-works">SEE HOW IT WORKS →</Link></div></section>

  <section className="uk-section uk-why"><div className="uk-section-head"><span className="uk-kicker">WHY UK RECOVERY</span><h2>Built Around Trust and Customer Choice</h2></div><div className="uk-feature-grid">{[["✓","VERIFIED PROFESSIONALS","Drivers and recovery companies must meet profile, document and admin approval requirements before participating."],["★","CUSTOMER CHOICE","Compare any available offers by price, ETA and verification details, then make your own choice."],["£","TRANSPARENT OFFERS","Indicative estimates and independently submitted offers help you understand possible costs."],["⌖","UK-WIDE NETWORK","A marketplace concept for connecting UK customers with independent recovery operators."]].map(([i,t,d])=><article key={t}><b>{i}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>

  <section className="marketplace"><div><span className="uk-kicker">A REAL MARKETPLACE</span><h2>Your Recovery. <em>Your Choice.</em></h2><p>In the planned marketplace, suitable approved drivers can submit their own offers. You compare options and choose — no automatic cheapest-price assignment.</p></div><div className="market-flow">{["Your Request","Suitable Drivers","Individual Offers","Your Choice"].map((x,i)=><span key={x}><b>{i+1}</b>{x}{i<3&&<em>→</em>}</span>)}</div></section>

  <section className="app-section" id="install-app"><div className="phone-mock"><div className="phone-screen"><span>UK Recovery</span><b>Need recovery?</b><small>Start a request in seconds.</small><i>GET RECOVERY ESTIMATE</i></div></div><div className="app-copy"><span className="uk-kicker">INSTALLABLE WEB APP</span><h2>Recovery Help in Your Pocket</h2><p>Add this demo website to your phone’s home screen for convenient access. Live job updates and push notifications are not available in this demo.</p><ul><li>Faster access when you need recovery</li><li>Explore the demonstration journey</li><li>View information about our marketplace</li><li>Easy access from your home screen</li></ul><InstallAppButton/><strong>No app store required.</strong><div className="install-guides"><span><b>iPhone</b>Open in Safari → Share → Add to Home Screen</span><span><b>Android</b>Open in Chrome → Install App</span></div></div></section>

  <section className="driver-cta" id="drivers"><div><span className="uk-kicker">FOR RECOVERY PROFESSIONALS</span><h2>Own a Recovery Business?</h2><p>The planned marketplace welcomes independent drivers and recovery companies. Create a profile, supply verification documents, receive admin approval and maintain a driver membership before receiving suitable opportunities and sending price and ETA offers. Registration and Stripe subscriptions are not yet live.</p><div><Link href="/driver/register" className="estimate-cta">BECOME A RECOVERY DRIVER →</Link><Link href="/driver/membership" className="driver-secondary">MEMBERSHIP INFORMATION</Link></div></div><div className="truck-visual"><span>24/7</span><b>RECOVERY</b><small>Professional marketplace opportunities</small></div></section>

  <section className="uk-section reviews" id="trust"><div className="uk-section-head"><span className="uk-kicker">MARKETPLACE PRINCIPLES</span><h2>Trust Starts With Transparency.</h2><p>We will only publish genuine feedback when it is available from verified completed recovery jobs. No sample ratings or fictional customer testimonials.</p></div><div className="review-grid">{[["01","Verification before participation","Driver profiles and relevant documents are reviewed for approval."],["02","Offers you can compare","See the price and estimated arrival time provided by each independent professional."],["03","Your decision, not an algorithm","Customers choose the recovery provider they prefer; the lowest bid is never selected automatically."]].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>

  <section className="uk-section home-payment" id="payments"><div className="uk-section-head"><span className="uk-kicker">PAYMENT CLARITY</span><h2>Pay Your Recovery Professional Directly.</h2><p>Customers pay their selected recovery driver or company directly. The platform does not process customer recovery payments in Phase 1.</p><p>This is currently a read-only client demo; no live customer recovery payments are available.</p></div></section>

  <section className="final-cta"><div><h2>Need Recovery?</h2><p>Explore how a request and customer choice would work. Live recovery bookings are not enabled in this client demo.</p></div><div><Link href="/recovery/request" className="estimate-cta">EXPLORE REQUEST DEMO →</Link><InstallAppButton/></div></section>

  <footer className="uk-footer"><div className="footer-main"><div><Link href="/" className="uk-logo"><span>UK</span><b>Recovery</b></Link><p>UK Recovery is a marketplace connecting customers with independent recovery providers.</p><InstallAppButton/></div><div><b>Customer</b><Link href="/recovery/request">Get Recovery</Link><Link href="/how-it-works">How It Works</Link><a href="#services">Services</a><a href="#payments">Payments</a><Link href="/login?mode=signup">Create Account</Link></div><div><b>Drivers</b><Link href="/driver/register">Become a Driver</Link><Link href="/login">Driver Login</Link><Link href="/driver/membership">Membership</Link></div><div><b>Company</b><Link href="/about">About</Link><Link href="/how-it-works">Customer Journey</Link><a href="#trust">Trust & Choice</a></div><div><b>Explore</b><Link href="/demo">Client Demo</Link><a href="#install-app">Install App</a><a href="#payments">Direct Payments</a></div></div><div className="footer-bottom-new">© {new Date().getFullYear()} UK Recovery · UK vehicle recovery marketplace · Read-only client demo</div></footer>
 </main>
}